= ADocBlog

A blog application that supports asciidoc format.

https://github.com/zemian/adocblog

== Features

The `adocblog` is a simple Java based web application for authors to publish and manage their
`Blog` posts. The application also allows admins to edit and manage the site as `Page` document.

.Blog managment
* Write blog post using `asciidoc` or `html` format.
* Store blog post in Postgres DB
* Updated blog post should be versioned.
* Allow specific content version to be published or unpublished.
* Provide UI to manage posts as admin users.
* Provide UI to view posts as public users.

.Page (site) management
* Write page doc using `FTL` (FreeMarker Template) format
* Store page doc in Postgres DB
* Updated page doc should be versioned.
* Allow specific content version to be published or unpublished.
* Provide UI to manage page docs as admin users.
* Provide UI to view page docs as public users.

== Requirements

* JDK8
* Maven3
* Tomcat8
* PostgreSQL9

== Build

  mvn package

== Application Deployment

The application is packaged into a `war` for distribution, and it should able to run in
any Servlet container hosting environment. There is a default `app.properties`
file that provide environment specific values. User should override this with they values in their
host env.

== User Guide

=== Setup

After a success build, you may create an admin user like this:

  mvn exec:java -Dexec.mainClass=com.zemian.adocblog.app.CreateUser -Dexec.args="--adminUser=true admin admin123"


=== Deployment

If you are using Apache Tomcat server, then simply copy the

Once deployed, for example on a localhost, you may open browser to

  http://localhost:8080/

The application is very easy to use with self-guided navigation. When you run it on a Servlet server,
your home page is the Public Users Viewing of blogger home. It should show latest posts with navigation
menu to older posts. User should able to search all posts for specific interests.

Majority part of the application functionalitie is at the Admin UI (eg: `http://localhost:8080/admin`).
Throught this, logged in users (authors or admins) may Create, Edit, Publish and manage their blog posts
or page documents.

== Design and Implementation

Development goals:

* Keep things simple, small and practical.
* Provide sensible default values.
* Allow extention if possible, but do not add complexity.

=== Technology Stack and Libraries

The following are choosen to implement the application.

* PostgreSQL 9.6
* JDK 8
* Spring 5 (MVC + JDBC modules only, no ORM)
* Servlet 3.1/JSP
* Bootstrap + jQuery and webjars
* AsciidoctorJ

=== Data and Domain Model Design

* A Settings table to allow configuration of application.
* A Users table to track blog authors and site admins.
* A general Doc and Content are defined to store content.
* A Doc may have one or more "versioned" Content.
* A Page is an Doc.
* A Blog is an extension of Doc with additional meta data.
* A Doc always has a associated "latest" Content version.
* A Doc may have an optional "published" Content version.

=== Blog and Page Content Management

App should allow user to write blog post in ASCIIDOC format. So the content is stored in `ADOC` format.
We also allow `HTML` format to be store as well.

At this point, versionning of a content is simply anther copy of the full content text. Every update
to the content will resulted in a new version. And the app allows you to publish with specific
version, while you may edit a new version as draft.

