= ADocBlog

A blog application that supports asciidoc format.

https://github.com/zemian/adocblog

== Features

The `adocblog` is a simple Java based web application for authors to publish and manage their
`Blog` posts. The application also allows admins to edit and manage the site as `Page` document.

.Blog managment
* Write blog post using `asciidoc` or `html` format.
* Store blog post in Postgres DB
* Updated blog post should be versioned.
* Allow specific content version to be published or unpublished.
* Provide UI to manage posts as admin users.
* Provide UI to view posts as public users.

.Page (site) management
* Write page doc using `FTL` (FreeMarker Template) format
* Store page doc in Postgres DB
* Updated page doc should be versioned.
* Allow specific content version to be published or unpublished.
* Provide UI to manage page docs as admin users.
* Provide UI to view page docs as public users.

== Requirements

* JDK8
* Maven3
* Tomcat8
* PostgreSQL9

== Build

  mvn package

== Application Deployment

The application is packaged into a `target/adocblog.war` for distribution, and it should able to run in
any Servlet container hosting environment. There is a default `app.properties`
file that provide environment specific values. User should override this with they values in their
host env.

== User Guide

=== Setup

After a success build, you may create an admin user like this:

  mvn exec:java -Dexec.mainClass=com.zemian.adocblog.app.CreateUser -Dexec.args="--adminUser=true admin admin123"


=== Deployment

If you are using Apache Tomcat server, then simply copy the `target/adocblog.war` file into
`$CATALINA_BASE/webapps` and start your server.

Once deployed, for example on a localhost, you may open browser to

  http://localhost:8080/adocblog

The application is very easy to use with self-guided navigation. When you run it on a Servlet server,
your home page is the Public Users Viewing of blogger home. It should show latest posts with navigation
menu to older posts. User should able to search all posts for specific interests. You would need to
publish the blog before it will shows up on the front page of the application.

To create and manage documents, go to the Admin Console here:

  http://localhost:8080/admin

Using the user you created above, you may login to Create, Edit, Publish and manage blog posts. If your
user is an "admin" user, then you may manage the site's `Page` content as well. For example you
may customize the "About" page by creating a new `Page` with Path = `themes/default/about.ftl`. You may
want to copy the content in `WEB-INF/ftl/themes/default/about.ftl` and modify it to your need.

NOTE: The Path of a `Page` is important, and they are being mapped in the application. If you mis-spelled
it, it will not find your version of the page.

NOTE: You must publish the `Page` before it can be viewed by the application!

== Design and Implementation

Development goals:

* Keep things simple, small and practical.
* Provide sensible default values.
* Allow extention if possible, but do not add complexity.

=== Technology Stack and Libraries

The following are choosen to implement the application.

* PostgreSQL 9.6
* JDK 8
* Spring 5 (MVC + JDBC modules only, no ORM for simplicity)
* Servlet 3.1
* FreeMarker Template 2.3
* Bootstrap + jQuery and webjars
* AsciidoctorJ

=== Data and Domain Model Design

* A Settings table to allow configuration of application.
* A Users table to track blog authors and site admins.
* A general Doc and Content are defined to store content.
* A Doc may have one or more "versioned" Content.
* A Page is an Doc.
* A Blog is an extension of Doc with additional meta data.
* A Doc always has a associated "latest" Content version.
* A Doc may have an optional "published" Content version.

=== Blog and Page Content Management

App should allow user to write blog post in ASCIIDOC format. So the content is stored in `ADOC` format.
We also allow `HTML` format to be store as well.

At this point, versionning of a content is simply anther copy of the full content text. Every update
to the content will resulted in a new version. And the app allows you to publish with specific
version, while you may edit a new version as draft.
