= ADocBlog
:author: Zemian Deng <zemiandeng@gamil.com>
:date: 2017-11-14

ADocBlog - A simple content management system.

The AdocBlog is a Java based web application that provides
CMS features. You may use it to write and manage blog and
site content in HTML or Asciidoc format. 

See release notes for full features.

Project Home: https://github.com/zemian/adocblog

Developer Blog: https://zemiandeng.com

== Quick Start

----
git clone https://github.com/zemian/adocblog
cd adocblog

# Setup PostgreSQL DB
createuser adocblog
createdb --owner=adocblog adocblog_dev
psql -U adocblog adocblog_dev < db/create-schema.sql

# Build adocblog war and run it
mvn package
java -jar target/dependency/webapp-runner.jar target/adocblog.war --port 8080
----

== Documentation

* link:userguide.adoc[User Guide]
* link:developer.adoc
* link:release.adoc

== License

   Copyright 2017-2018 Zemian Deng

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

See link:LICENSE
