= ADocBlog

A blog application that supports asciidoc format.

https://github.com/zemian/adocblog

== User Guide

Get a release distribution package and unzip it:

  cd $HOME/apps
  unzip adocblog-<version>.zip
  cd adocblog-<version>


=== Setup Database

Initialize a new PostgreSQL database.

  bin/init-db.sh


=== Add application users

  bin/user-tool.sh --create --adminUser=true --fullName="Mr. Admin" admin admin123


=== Setup the bundled server

  bin/server.sh --port 8080


Once deployed, for example on a localhost, you may open browser to

  http://localhost:8080/

The application is very easy to use with self-guided navigation. When you run it on a Servlet server,
your home page is the Public Users Viewing of blogger home. It should show latest posts with navigation
menu to older posts. User should able to search all posts for specific interests. You would need to
publish the blog before it will shows up on the front page of the application.

To create and manage documents, go to the Admin Console here:

  http://localhost:8080/admin

Using the user you created above, you may login to Create, Edit, Publish and manage blog posts. If your
user is an "admin" user, then you may manage the site's `Page` content as well.

NOTE: You must publish the document before it can be viewed by the application!
