= Developer Guide

ADocBlog - A simple content management system.

The AdocBlog is a Java based web application that provides
CMS features. You may use it to write and manage blog and
site content in HTML or Asciidoc format.

== Please read UserGuide first

You should see the link:../readme.adoc[Project Readme] and link:userguide.adoc[User Guide]
before this development guide. Those docs explain how to setup and run ADocBlog as user
before you need to modify any code.

== Build From Source

=== Required Software

* Java 8+
* Apache Maven 3.5+
* PostgreSQL 9.4+
* Git 1.7.10 +

=== Quick Build

	git clone https://github.com/zemian/adocblog
	cd adocblog
	mvn package

If you want to skip tests, run `mvn package -DskipTests`. To successfully run the unit tests,
it requires you to setup a local PostgreSQL DB named 'adocblog_dev', and its schema.

If you want to build from a release tag, you would want to package with a release file:

  mvn package -P with-release-file

This would include the Git version and commit hash id into the war that you can inspect at
runtime under SystemInfo.

== How to Change Crypto Service Encryption Key

If you were to make a new environment config set (See link:userguide.adoc[User Guide]), then
it's recommend that you also generate a new set of encryption key and salt iv with random string
to be more secured. We provide tool to help you generate random strings:

	java -cp "config:target/classes:target/adocblog/WEB-INF/lib/*" com.zemian.adocblog.app.RandomTool 16

Above tool will generate 5 random strings that you may choose to use in `app.properties`. You need
to update these two lines:

	app.crypto.key = myNewRandomeString
	app.crypto.ivParam = myNewRandomeString
	app.crypto.algorithm = AES/CBC/PKCS5Padding

You may continue to use `AES/CBC/PKCS5Padding` because it's considered fairly secured for data
encryption.

Once you setup the new config set (eg: `myenv`) then you may use our Crypto tool to re-encrypt
the DB password like this:

	java -cp "config:target/classes:target/adocblog/WEB-INF/lib/*" \
	-Dadocblog.env=myenv \
	com.zemian.adocblog.app.CryptoTool mySecretPassword

Next, replace the output of the encrypted password with your plain password in config file.

== Print Released Version Props

If you build package with `-P with-version-file`, then this tool should print these info:

	java -cp "config:target/classes:target/adocblog/WEB-INF/lib/*" \
	com.zemian.adocblog.app.PrintVersionProps
